sonar.projectKey=sitio_anuncios
sonar.projectName=sitio_anuncios
sonar.projectVersion=1.0

# Indicar que el código fuente a analizar está en la raíz
sonar.sources=.

# Exclusiones de archivos sensibles, entorno virtual, BD y temporales
sonar.exclusions=**/.env, **/env/**, **/.venv/**, **/db.sqlite3, **/media/**, **/static/**, **/__pycache__/**
