# Generated by Django 5.2.15 on 2026-07-13 20:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_anuncio_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='anuncios.categoria'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ImagenAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='anuncios_fotos/')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_adicionales', to='anuncios.anuncio')),
            ],
        ),
    ]
