# Generated by Django 5.2.15 on 2026-08-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_remove_anuncio_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='dias_duracion',
            field=models.IntegerField(default=30, verbose_name='Días de Duración'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Pago'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
