# Generated by Django 5.2.15 on 2026-08-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_anuncio_dias_duracion_anuncio_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='telegram',
            field=models.CharField(blank=True, help_text='Ejemplo: TuUsuarioTelegram (sin @)', max_length=50, null=True, verbose_name='Usuario de Telegram'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Ejemplo: 573000000000', max_length=20, null=True, verbose_name='Número de WhatsApp'),
        ),
    ]
