# Generated by Django 5.2.15 on 2026-08-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_anuncio_telegram_anuncio_whatsapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Anuncio', 'verbose_name_plural': 'Anuncios'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='imagenanuncio',
            options={'verbose_name': 'Imagen Adicional', 'verbose_name_plural': 'Imágenes Adicionales'},
        ),
    ]
